name: esp32_oled_app
description: "ESP32-C3 OLED 蓝牙配网应用"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.32.0
  permission_handler: ^11.0.1
  wifi_iot: ^0.3.3
  image_picker: ^1.0.0
  image: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
